192.78.98.48
[frontend]
192.78.98.45
192.78.98.46
192.78.98.47

[backend]
192.78.98.45
192.78.98.46
192.78.98.47

[web]
54.160.132.13

[practice]
54.160.132.13 ansible_user=ec2-user ansible_password=DevOps321

[roboshop:children]
frontend
backend

[local]
localhost

; [local]
; localhost ansible_connection=local

[local:vars]
COURSE=Ansible from inventory
NAME=Variable from inventory